# Kunci API dan URL Anda
GEMINI_API = "AIzaSyDwpv0KP6FezXRfhQiR3rJ6jsErfDN7M_0"
GSHEET_URL = "https://docs.google.com/spreadsheets/d/1mAN_j4bUQtXk4_oY3nszPXhyKmhV6s1zwKyHuwU4_gQ/edit?gid=0#gid=0"
[connections.gcs]
type = "service_account"
project_id = "gen-lang-client-0844197394"
private_key_id = "6d7726244972842712ac568777d35e189c3d1dbf"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCRoHpohcGvSZ+q
rnC29f4ffaymYjwfHAIFMclWmM+SDcPoE6JKTB1Cxkqs4SlY0PS+YsL+rp5J0VZ6
GEc8JsjZW2RRlgtxINeqkyz8cgiWRpkJzX22xojGKqVsmP9LJvz2kCGam2hC7FRG
p0fesPo5dwQhHw1IRdHGBIxuGOuHvy0kEbqdmTtLUo5EWBWm5+HDryL73NYN5ugB
bPyXsdf1ojNk/SQ3+we4l8peDylW8UNzuwouIHeMc2dMNSSVu2qEh0/JwpD8tBA4
QA/aN5Yb0HmGYTEIrlzKiAi8JnnBT+yRGzaRc4WgRGf5oqOg7MpVqgEmE7uFy9zh
sUDNgTudAgMBAAECggEANQyiyuS+8938Hi9BvETMeChN9qaehC6txbqnP7aXFvuQ
vEA6xJoJpsOZfHThnQsxvRE5O5Hc88Mgn4WsnYr7a8LRPq9MJ7/xEKBgqO3ZlvTM
1zdWbnjQZnAupurtRTFEwYUr2Kh4SLjS0pIpqkQKQ1jJ1k77hbJ5gosxpQHK+z3q
vEA6xJoJpsOZfHThnQsxvRE5O5Hc88Mgn4WsnYr7a8LRPq9MJ7/xEKBgqO3ZlvTM
1zdWbnjQZnAupurtRTFEwYUr2Kh4SLjS0pIpqkQKQ1jJ1k77hbJ5gosxpQHK+z3q
"""
client_email = "google@gen-lang-client-0844197394.iam.gserviceaccount.com"
client_id = "110264457901015983623"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/google%40gen-lang-client-0844197394.iam.gserviceaccount.com"
universe_domain = "googleapis.com"